package com.github.tt4g.learn.antlr;

import edu.umd.cs.findbugs.annotations.NonNull;
import org.antlr.v4.runtime.ANTLRErrorListener;
import org.antlr.v4.runtime.ConsoleErrorListener;
import org.antlr.v4.runtime.Lexer;

abstract class LexerUtils {

    private LexerUtils() {

    }

    /**
     * Remove all default {@link ANTLRErrorListener}.<br>
     *
     * {@link Lexer} generated by ANTLR v4 has default {@link ANTLRErrorListener}
     * ({@link ConsoleErrorListener}).
     * This method remove these listeners.
     *
     * @param lexer {@link Lexer}
     */
    static void removeDefaultErrorListener(@NonNull Lexer lexer) {
        // Remove default listeners (`ConsoleErrorListener`).
        lexer.removeErrorListeners();
    }

}
